# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: HendrikVrey.Sling
PackageVersion: 1.1.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- http
- rest
ProductCode: '{7C4E1B2A-9F63-4D18-A5E7-2B90C6F4A831}_is1'
ReleaseDate: 2026-09-28
AppsAndFeaturesEntries:
- DisplayName: Sling
  Publisher: Hendrik Vrey
  ProductCode: '{7C4E1B2A-9F63-4D18-A5E7-2B90C6F4A831}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/HendrikVrey/Sling/releases/download/v1.1.0/Sling-Setup.exe
  InstallerSha256: 29B8F052A29174C1D8D96EBAC6418DF9B002A57B1653BB0D4215BAEB9467528C
- Architecture: arm64
  InstallerUrl: https://github.com/HendrikVrey/Sling/releases/download/v1.1.0/Sling-Setup.exe
  InstallerSha256: 29B8F052A29174C1D8D96EBAC6418DF9B002A57B1653BB0D4215BAEB9467528C
ManifestType: installer
ManifestVersion: 1.10.0
